Repository debauchee/barrier, pull requests merged in 2019-09, with the labels that each got.

#422 [README] update README with info about packages
  README.md
Labels: doc, enhancement

#424 Merged mouse drift fix from synergy-core
  src/lib/platform/OSXScreen.h
  src/lib/platform/OSXScreen.mm
Labels: enhancement

#439 Fix debug build launch
  clean_build.bat
Labels: bug, windows
