Repository debauchee/barrier, pull requests merged in 2021-01, with the labels that each got.

#600 Create italian.iss
  dist/inno/scripts/lang/italian.iss
Labels: enhancement, installer/package, no-pr-activity

#536 translation: ja-JP
  src/gui/langbuild.cmd
  src/gui/res/lang/gui_ja-JP.qm
  src/gui/res/lang/gui_ja-JP.ts
Labels: enhancement

#607 reversed aliases: val, key to key, val. add barebones example
  doc/barrier.conf.example-advanced
  doc/barrier.conf.example-barebones
  doc/barrier.conf.example-basic
Labels: doc, no-pr-activity
